spring.application.name=ecommerce

server.port=${PORT:${SERVER_PORT:8080}}

spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=${MONGODB_URI}

app.jwt.secret=${JWT_SECRET:VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JEZXY=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}